import vine from '@vinejs/vine'

/**
 * Message validators for the relay service.
 *
 * SECURITY:
 * - Blob content is NOT validated beyond size limits — it is opaque encrypted data.
 * - We validate structure (required fields, types) but never inspect content.
 * - Maximum blob size prevents memory exhaustion attacks.
 * - Device token format is validated to prevent injection attacks on Redis keys.
 */

/**
 * Maximum encrypted blob size in bytes (base64 encoded).
 *
 * 256 KB supports:
 * - Text messages (typically < 10 KB encrypted)
 * - Media key bundles (< 1 KB)
 * - Pre-key messages with ratchet state (< 5 KB)
 * - Group sender key distributions (< 20 KB)
 *
 * Actual media (images, videos, files) is encrypted and uploaded
 * directly to object storage by the client. Only the media key
 * (which is tiny) transits through this relay.
 */
const MAX_BLOB_SIZE = 256 * 1024

/**
 * Device token format: UUID v4 or similar opaque identifier.
 * Must be alphanumeric with hyphens, 32-128 characters.
 * This regex prevents Redis key injection via specially crafted device IDs.
 */
const DEVICE_ID_REGEX = /^[a-zA-Z0-9\-]{32,128}$/

/**
 * Message ID format: client-generated UUID v4.
 * Used for deduplication and acknowledgment.
 */
const MESSAGE_ID_REGEX = /^[a-f0-9\-]{36}$/

/**
 * Validator for POST /v1/messages/send
 *
 * Validates the message envelope structure WITHOUT inspecting
 * the encrypted blob content.
 */
export const sendMessageValidator = vine.compile(
  vine.object({
    /** Unique message identifier generated by the sender client. */
    messageId: vine.string().regex(MESSAGE_ID_REGEX),

    /** Target device identifier. Opaque, no user identity. */
    recipientDeviceId: vine.string().regex(DEVICE_ID_REGEX),

    /**
     * The encrypted blob as a base64-encoded string.
     * Content is opaque — the server CANNOT and MUST NOT decrypt this.
     * Only the size is validated to prevent abuse.
     */
    blob: vine.string().maxLength(MAX_BLOB_SIZE),

    /**
     * Sender's device identifier — passed in clear so the recipient
     * can address SessionCipher / look up the right Signal session.
     *
     * Privacy trade-off (documented): the relay sees who's sending to
     * whom in clear. This is acceptable for the MVP because the relay
     * already correlates source IP → recipient deviceId at the TCP
     * layer. Sealed Sender (Signal's mechanism that hides this from
     * the relay) lands in v2 and will use a per-session token here
     * instead. Until then, the relay's controller MUST NOT log this
     * field — and currently doesn't.
     */
    senderDeviceId: vine.string().regex(DEVICE_ID_REGEX),

    /**
     * Sender's accountId — needed by the recipient to render the
     * sender's profile (username, displayName) on a first-contact
     * message. Same privacy trade-off as senderDeviceId; same
     * "delete-on-deliver" lifecycle so it's not stored long-term.
     */
    senderAccountId: vine.string().minLength(8).maxLength(64),
  })
)

/**
 * Validator for GET /v1/messages/pending
 *
 * The device ID comes from the authenticated request context,
 * not from user input, but we validate it defensively.
 */
export const pendingMessagesValidator = vine.compile(
  vine.object({
    deviceId: vine.string().regex(DEVICE_ID_REGEX),
  })
)

/**
 * Validator for DELETE /v1/messages/:id
 *
 * Validates the message ID format from the URL parameter.
 */
export const acknowledgeValidator = vine.compile(
  vine.object({
    id: vine.string().regex(MESSAGE_ID_REGEX),
  })
)
