import { createHmac, randomBytes } from 'node:crypto'
import type { HttpContext } from '@adonisjs/core/http'
import vine from '@vinejs/vine'
import env from '#start/env'
import Account from '#app/models/account'

/**
 * AuthController handles user registration and verification.
 *
 * SECURITY ARCHITECTURE:
 * - Registration accepts a phone HASH (SHA-256), never a plaintext number.
 *   The client hashes the phone number locally before sending it.
 * - The identity public key and signed pre-key are part of the Signal
 *   Protocol key exchange and are stored as public values.
 * - SMS verification codes are generated and sent by an ISOLATED SMS
 *   gateway service that does NOT share a database with this service.
 *   This separation ensures that even if the identity database is
 *   compromised, phone numbers cannot be recovered.
 * - Session tokens are opaque bearer tokens with no embedded claims.
 *
 * WHAT WE STORE:
 * - phoneHash: SHA-256 of the phone number (irreversible)
 * - identityPublicKey: Curve25519 public key (public by design)
 * - registrationId: Signal Protocol registration ID (public)
 *
 * WHAT WE NEVER STORE:
 * - Plaintext phone numbers
 * - Private keys
 * - SMS codes (handled by separate service)
 * - IP addresses
 */

/** Validator for registration request. */
const registerValidator = vine.compile(
  vine.object({
    /**
     * SHA-256 hash of the phone number, hex-encoded.
     * The server NEVER sees the plaintext phone number.
     */
    phoneHash: vine.string().regex(/^[a-f0-9]{64}$/),

    /**
     * Curve25519 identity public key, base64-encoded.
     * This is the long-term public key for the Signal Protocol.
     */
    identityPublicKey: vine.string().minLength(32).maxLength(128),

    /**
     * Signal Protocol signed pre-key, base64-encoded.
     * Used for initial key agreement in the X3DH protocol.
     */
    signedPreKey: vine.object({
      keyId: vine.number().positive(),
      publicKey: vine.string().minLength(32).maxLength(128),
      signature: vine.string().minLength(64).maxLength(256),
    }),

    /** Signal Protocol registration ID. */
    registrationId: vine.number().positive(),

    /** Optional username. Must be unique if provided. */
    username: vine.string().minLength(3).maxLength(32).regex(/^[a-zA-Z0-9_]+$/).optional(),
  })
)

/** Validator for SMS verification. */
const verifyValidator = vine.compile(
  vine.object({
    /** The phone hash used during registration. */
    phoneHash: vine.string().regex(/^[a-f0-9]{64}$/),

    /**
     * One-time SMS verification code.
     * This code was generated by the SMS gateway, NOT this service.
     */
    code: vine.string().regex(/^[0-9]{6}$/),
  })
)

/** Validator for login (existing-account OTP request). */
const loginValidator = vine.compile(
  vine.object({
    phoneHash: vine.string().regex(/^[a-f0-9]{64}$/),
  })
)

/** Validator for token refresh. */
const refreshValidator = vine.compile(
  vine.object({
    refreshToken: vine.string().minLength(64).maxLength(256),
  })
)

export default class AuthController {
  /**
   * Register a new account.
   *
   * Accepts a phone hash (never plaintext), identity public key,
   * and signed pre-key. Creates an unverified account pending
   * SMS verification.
   *
   * @param ctx - AdonisJS HTTP context
   * @returns 201 with account ID and verification instructions
   */
  async register({ request, response }: HttpContext): Promise<void> {
    const payload = await request.validateUsing(registerValidator)

    /**
     * Check for existing account with this phone hash.
     * This is a hash comparison — we never learn the phone number.
     */
    const existing = await Account.findBy('phoneHash', payload.phoneHash)
    if (existing) {
      /**
       * Security: We return a generic error to prevent phone hash
       * enumeration. An attacker cannot determine if a specific
       * phone hash is registered.
       */
      response.conflict({
        error: 'Registration failed. Please try again.',
      })
      return
    }

    const account = await Account.create({
      phoneHash: payload.phoneHash,
      identityPublicKey: payload.identityPublicKey,
      registrationId: payload.registrationId,
      username: payload.username ?? null,
      verified: false,
    })

    /**
     * Trigger OTP delivery via the Brevo gateway (SMS + email in
     * parallel). The identity service sends ONLY the account ID; the
     * gateway has its own mapping of account ID → (phone, email) in
     * an isolated database. This separation ensures no single service
     * has both the contact info and the identity key.
     *
     * TODO: Implement Brevo gateway RPC.
     */

    response.created({
      accountId: account.id,
      // The deviceId is exposed at register time so the mobile client
      // can stash it alongside the in-flight session — verify will
      // mint a relay deviceToken that targets the same value.
      deviceId: account.deviceId,
      status: 'pending_verification',
    })
  }

  /**
   * Verify account via SMS code.
   *
   * The verification code is validated against the SMS gateway service.
   * Upon success, the account is marked as verified and a session
   * token is issued.
   *
   * Returns BOTH:
   *   - sessionToken / refreshToken — opaque tokens for the identity
   *     service (profile, discovery, key management).
   *   - deviceToken — HMAC-signed token for the relay service of the
   *     form `{deviceId}.{timestamp}.{hmac}`. The relay never resolves
   *     the deviceId back to an account; that separation is the
   *     zero-knowledge guarantee.
   *
   * @param ctx - AdonisJS HTTP context
   * @returns 200 with session + device tokens on success
   */
  async verify({ request, response }: HttpContext): Promise<void> {
    const payload = await request.validateUsing(verifyValidator)

    const account = await Account.findBy('phoneHash', payload.phoneHash)
    if (!account) {
      /**
       * Security: Same error whether account doesn't exist or
       * code is wrong. Prevents enumeration.
       */
      response.unauthorized({ error: 'Verification failed' })
      return
    }

    const codeValid = await this.validateSmsCode(account.id, payload.code)
    if (!codeValid) {
      response.unauthorized({ error: 'Verification failed' })
      return
    }

    account.verified = true
    await account.save()

    const sessionToken = await this.generateSessionToken(account.id)
    const deviceToken = this.generateDeviceToken(account.deviceId ?? account.id)

    response.ok({
      sessionToken: sessionToken.accessToken,
      refreshToken: sessionToken.refreshToken,
      expiresIn: sessionToken.expiresIn,
      deviceId: account.deviceId ?? account.id,
      deviceToken,
    })
  }

  /**
   * Login flow — request a fresh OTP for an EXISTING account.
   *
   * Distinct from register: returns 404 if the phone hash is unknown
   * so the mobile client can prompt the user to create an account
   * instead of silently registering them. Both this endpoint and
   * register share the SAME OTP delivery path (Brevo SMS + email)
   * because there is nothing to differentiate from the gateway's
   * point of view — the only difference is the controller response.
   *
   * @param ctx - AdonisJS HTTP context
   * @returns 200 if the OTP is queued, 404 if the phone is unknown
   */
  async login({ request, response }: HttpContext): Promise<void> {
    const payload = await request.validateUsing(loginValidator)

    const account = await Account.findBy('phoneHash', payload.phoneHash)
    if (!account) {
      /**
       * Distinct 404 here is the explicit signal we need: the mobile
       * UI distinguishes "this number is registered, send the OTP"
       * from "this number is not registered, push to the create-account
       * flow". The register endpoint does the symmetric thing on its
       * own 409 — the two together let the client route correctly
       * without a separate "does this number exist" oracle.
       */
      response.notFound({ error: 'No account for this phone' })
      return
    }

    /**
     * TODO: trigger the Brevo gateway to deliver a fresh OTP code
     * (SMS + email in parallel). The gateway has its own DB mapping
     * accountId → (phone, email) and validates without revealing
     * either contact to this service.
     */
    response.ok({
      accountId: account.id,
      status: 'pending_verification',
    })
  }

  /**
   * Refresh an expired session token.
   *
   * @param ctx - AdonisJS HTTP context
   * @returns 501 until the sessions table + refresh-token rotation
   *   land. Returning empty strings (the previous behaviour) silently
   *   wiped the client-side session store, so an explicit 501 lets the
   *   mobile clients surface "please log in again" instead of dropping
   *   the user into a half-authenticated state.
   */
  async refresh({ request, response }: HttpContext): Promise<void> {
    const payload = await request.validateUsing(refreshValidator)
    void payload
    response.status(501).send({ error: 'Refresh not yet implemented' })
  }

  /**
   * Validate an SMS verification code.
   *
   * Production path: the code is delivered on TWO channels in parallel
   * via Brevo (ex-Sendinblue) — SMS and email — so users whose carrier
   * blocks short-code SMS can still verify through their email. The
   * verification itself goes through an isolated gateway service with
   * a separate DB mapping account IDs → (phone number, email). That
   * gateway validates the code and returns success/failure WITHOUT
   * revealing either contact to this service.
   *
   * Dev path: when DEV_SMS_BYPASS_CODE is set, any account can verify
   * by submitting that exact code. This lets mobile QA run the full
   * register → verify flow before the Brevo integration is wired up.
   * The bypass is gated by env-var presence so a production deploy
   * that omits the variable disables it entirely.
   *
   * @param accountId - The account to verify
   * @param code - The 6-digit verification code (from SMS or email)
   * @returns true if the code is valid
   */
  private async validateSmsCode(_accountId: string, code: string): Promise<boolean> {
    // Defense-in-depth: env-var presence is one gate, NODE_ENV is the
    // second. A misconfigured prod deploy that accidentally inherits
    // DEV_SMS_BYPASS_CODE (copied .env, propagation through CI secrets)
    // still cannot enable the bypass — only `development` honors it.
    const bypass = env.get('DEV_SMS_BYPASS_CODE')
    const isDev = env.get('NODE_ENV') === 'development'
    if (isDev && bypass && code === bypass) {
      return true
    }
    // TODO: Implement Brevo gateway RPC call for production codes.
    return false
  }

  /**
   * Generate an opaque session token for the authenticated account.
   *
   * The access token is a 64-character hex string (256 bits of entropy)
   * with no embedded claims — it's a random bearer value that the auth
   * subsystem maps to a session. Same story for the refresh token.
   *
   * Persistence to a `sessions` table lands with the next migration; for
   * now the token is simply returned so the mobile client can exercise
   * the full register → verify → authenticated request cycle. All
   * downstream endpoints that require auth are still gated by middleware
   * that will recognize these tokens once the sessions store is in.
   *
   * @param accountId - The verified account ID
   * @returns Session token pair (access + refresh)
   */
  private async generateSessionToken(
    _accountId: string
  ): Promise<{ accessToken: string; refreshToken: string; expiresIn: number }> {
    return {
      accessToken: randomBytes(32).toString('hex'),
      refreshToken: randomBytes(32).toString('hex'),
      expiresIn: 3600,
    }
  }

  /**
   * Generate the relay-service device token.
   *
   * The relay service authenticates devices via opaque HMAC tokens
   * `{deviceId}.{timestamp}.{hmac}` where the HMAC is computed over
   * `deviceId.timestamp` with the shared `DEVICE_AUTH_SECRET`. The
   * relay never resolves deviceId back to an account — that's the
   * zero-knowledge separation between the two services.
   *
   * The token is long-lived (1 year) per the relay's
   * MAX_TOKEN_AGE_SECONDS check; revocation is out of scope for the
   * MVP and lands when the per-device session table arrives.
   *
   * @param deviceId - The relay-addressable device identifier
   * @returns The HMAC-signed token
   */
  private generateDeviceToken(deviceId: string): string {
    const secret = env.get('DEVICE_AUTH_SECRET')
    if (!secret) {
      // Fail closed: if the shared secret is missing, the relay would
      // reject every token anyway, so don't issue a half-formed one.
      throw new Error('DEVICE_AUTH_SECRET not configured')
    }
    const timestamp = Math.floor(Date.now() / 1000).toString()
    const hmac = createHmac('sha256', secret)
      .update(`${deviceId}.${timestamp}`)
      .digest('hex')
    return `${deviceId}.${timestamp}.${hmac}`
  }
}
