import type { HttpContext } from '@adonisjs/core/http'
import vine from '@vinejs/vine'
import Account from '#app/models/account'

/**
 * AuthController handles user registration and verification.
 *
 * SECURITY ARCHITECTURE:
 * - Registration accepts a phone HASH (SHA-256), never a plaintext number.
 *   The client hashes the phone number locally before sending it.
 * - The identity public key and signed pre-key are part of the Signal
 *   Protocol key exchange and are stored as public values.
 * - SMS verification codes are generated and sent by an ISOLATED SMS
 *   gateway service that does NOT share a database with this service.
 *   This separation ensures that even if the identity database is
 *   compromised, phone numbers cannot be recovered.
 * - Session tokens are opaque bearer tokens with no embedded claims.
 *
 * WHAT WE STORE:
 * - phoneHash: SHA-256 of the phone number (irreversible)
 * - identityPublicKey: Curve25519 public key (public by design)
 * - registrationId: Signal Protocol registration ID (public)
 *
 * WHAT WE NEVER STORE:
 * - Plaintext phone numbers
 * - Private keys
 * - SMS codes (handled by separate service)
 * - IP addresses
 */

/** Validator for registration request. */
const registerValidator = vine.compile(
  vine.object({
    /**
     * SHA-256 hash of the phone number, hex-encoded.
     * The server NEVER sees the plaintext phone number.
     */
    phoneHash: vine.string().regex(/^[a-f0-9]{64}$/),

    /**
     * Curve25519 identity public key, base64-encoded.
     * This is the long-term public key for the Signal Protocol.
     */
    identityPublicKey: vine.string().minLength(32).maxLength(128),

    /**
     * Signal Protocol signed pre-key, base64-encoded.
     * Used for initial key agreement in the X3DH protocol.
     */
    signedPreKey: vine.object({
      keyId: vine.number().positive(),
      publicKey: vine.string().minLength(32).maxLength(128),
      signature: vine.string().minLength(64).maxLength(256),
    }),

    /** Signal Protocol registration ID. */
    registrationId: vine.number().positive(),

    /** Optional username. Must be unique if provided. */
    username: vine.string().minLength(3).maxLength(32).regex(/^[a-zA-Z0-9_]+$/).optional(),
  })
)

/** Validator for SMS verification. */
const verifyValidator = vine.compile(
  vine.object({
    /** The phone hash used during registration. */
    phoneHash: vine.string().regex(/^[a-f0-9]{64}$/),

    /**
     * One-time SMS verification code.
     * This code was generated by the SMS gateway, NOT this service.
     */
    code: vine.string().regex(/^[0-9]{6}$/),
  })
)

/** Validator for token refresh. */
const refreshValidator = vine.compile(
  vine.object({
    refreshToken: vine.string().minLength(64).maxLength(256),
  })
)

export default class AuthController {
  /**
   * Register a new account.
   *
   * Accepts a phone hash (never plaintext), identity public key,
   * and signed pre-key. Creates an unverified account pending
   * SMS verification.
   *
   * @param ctx - AdonisJS HTTP context
   * @returns 201 with account ID and verification instructions
   */
  async register({ request, response }: HttpContext): Promise<void> {
    const payload = await request.validateUsing(registerValidator)

    /**
     * Check for existing account with this phone hash.
     * This is a hash comparison — we never learn the phone number.
     */
    const existing = await Account.findBy('phoneHash', payload.phoneHash)
    if (existing) {
      /**
       * Security: We return a generic error to prevent phone hash
       * enumeration. An attacker cannot determine if a specific
       * phone hash is registered.
       */
      response.conflict({
        error: 'Registration failed. Please try again.',
      })
      return
    }

    const account = await Account.create({
      phoneHash: payload.phoneHash,
      identityPublicKey: payload.identityPublicKey,
      registrationId: payload.registrationId,
      username: payload.username ?? null,
      verified: false,
    })

    /**
     * Trigger SMS verification via the isolated SMS gateway.
     * The identity service sends ONLY the account ID to the gateway.
     * The gateway has its own mapping of account ID → phone number
     * (encrypted, separate database). This architectural separation
     * ensures no single service has both the phone number and the
     * identity key.
     *
     * TODO: Implement SMS gateway integration.
     */

    response.created({
      accountId: account.id,
      status: 'pending_verification',
    })
  }

  /**
   * Verify account via SMS code.
   *
   * The verification code is validated against the SMS gateway service.
   * Upon success, the account is marked as verified and a session
   * token is issued.
   *
   * @param ctx - AdonisJS HTTP context
   * @returns 200 with session token on success
   */
  async verify({ request, response }: HttpContext): Promise<void> {
    const payload = await request.validateUsing(verifyValidator)

    const account = await Account.findBy('phoneHash', payload.phoneHash)
    if (!account) {
      /**
       * Security: Same error whether account doesn't exist or
       * code is wrong. Prevents enumeration.
       */
      response.unauthorized({ error: 'Verification failed' })
      return
    }

    /**
     * TODO: Validate the SMS code against the SMS gateway service.
     * This involves an internal RPC call to the isolated SMS service.
     * The SMS service validates the code and returns success/failure
     * WITHOUT revealing the phone number to us.
     */
    const codeValid = await this.validateSmsCode(account.id, payload.code)
    if (!codeValid) {
      response.unauthorized({ error: 'Verification failed' })
      return
    }

    account.verified = true
    await account.save()

    /**
     * Generate an opaque session token.
     * This token contains NO user information — it's a random value
     * that maps to a session in the auth subsystem.
     */
    const sessionToken = await this.generateSessionToken(account.id)

    response.ok({
      sessionToken: sessionToken.accessToken,
      refreshToken: sessionToken.refreshToken,
      expiresIn: sessionToken.expiresIn,
    })
  }

  /**
   * Refresh an expired session token.
   *
   * @param ctx - AdonisJS HTTP context
   * @returns 200 with new session token
   */
  async refresh({ request, response }: HttpContext): Promise<void> {
    const payload = await request.validateUsing(refreshValidator)

    /**
     * TODO: Validate payload.refreshToken and issue new access token.
     * Refresh tokens are single-use — after rotation, the old refresh
     * token is invalidated to prevent replay.
     */
    void payload

    response.ok({
      sessionToken: '',
      refreshToken: '',
      expiresIn: 3600,
    })
  }

  /**
   * Validate an SMS verification code via the isolated SMS gateway.
   *
   * This is an internal RPC call. The SMS gateway is a separate
   * service with its own database that maps account IDs to phone
   * numbers. This architectural separation ensures that even if
   * the identity database is fully compromised, phone numbers
   * cannot be recovered.
   *
   * @param accountId - The account to verify
   * @param code - The 6-digit SMS code
   * @returns true if the code is valid
   */
  private async validateSmsCode(_accountId: string, _code: string): Promise<boolean> {
    // TODO: Implement SMS gateway RPC call
    return false
  }

  /**
   * Generate an opaque session token for the authenticated account.
   *
   * @param accountId - The verified account ID
   * @returns Session token pair (access + refresh)
   */
  private async generateSessionToken(
    _accountId: string
  ): Promise<{ accessToken: string; refreshToken: string; expiresIn: number }> {
    // TODO: Implement token generation via @adonisjs/auth
    return {
      accessToken: '',
      refreshToken: '',
      expiresIn: 3600,
    }
  }
}
